### ISSUE TITLE
Show the executed git command in the log

### ISSUE THREAD

**Issue by rustyx** [gitahead/gitahead#259]
Currently it's not possible to see what actual Git command is executed.
Please add an option to show the executed git command in the log (would also be nice to have the log written to a file).

**Comment by hackhaslam** [comment]
GitAhead doesn't shell out to command line `git`. It uses the `libgit2` library. The log could report the *equivalent* git command, but that might be misleading.

**Comment by ingank** [comment]
ah ok, one another user is looking for this (option)...
The question is, can there be thinkable **a option** in GitAhead, that is pointed to the **possibility** of writing git-commands instead of libgit2 - api messages?
sorry thats comming arround, when the speaker is'nt knowing, what he is talking about.
