### ISSUE TITLE
Add auto refresh

### ISSUE THREAD

**Issue by Croydon** [gitahead/gitahead#318]
My git repository are often manipulated by other applications as well

I'm new to gitahead and was honestly confused several times why it doesn't pick up changes done to the git repository/repositories, until I noticed that there is a refresh option

My expectation would be that githead is regularly auto refreshing the repository which is in focus

If there are concerns about performance on some machines and/or repositories this could be an opt-out option.

Thanks for all the work on gitahead, from what I have seen so far it is pretty decent!

**Comment by hackhaslam** [comment]
GitAhead does watch files in the working directory and automatically refresh when they change. The refresh button is there for a few cases where manual refresh is still needed. What platform are you on? If you touch a file in the working directory, does GitAhead refresh?

**Comment by Croydon** [comment]
Uncommited file changes do refresh themselves automatically as expected

What is not working, e.g.:
  1. Make a file change to disk
  2. Optional: If switching now to gitahead the file change is loaded and displayed in the uncommited changes section
  3. Third-party program performs now (for example) a git commit
  4. Switch to gitahead. gitahead will never reload the git repository's information and won't notice/display the new commit
   5. If step 2) was performed, gitahead will even continue to display the file change, which is now already commited

Similar behaviour for git rebases, merges and other git manipulations

**Comment by asvc** [comment]
I have noticed the same when file is located on a network share, even if such share is pointing to a pseudo-fs on the local computer.

Steps to reproduce:
1. Mount WSL, `\\wsl$\your-wsl-instance-name\`
2. Open repository from GitAhead GUI
3. Change something

Environment:
```
GitAhead v2.6.3
Windows v10.0.19041.0
Git v2.28.0.windows.1
```

**Comment by keywinf** [comment]
No autorefresh for me on my mac. Single feature it lacks, because I'm very satisfied besides :)

**Comment by jwestell** [comment]
> GitAhead does watch files in the working directory and automatically refresh when they change. The refresh button is there for a few cases where manual refresh is still needed. What platform are you on? If you touch a file in the working directory, does GitAhead refresh?

I think the auto-refresh behaviour would be improved by watching not only the working directory but also the .git/ directory. This comment here suggests this was considered at one time:
https://github.com/gitahead/gitahead/blob/bb747caef098140d9674990b1d79d096d1eac8df/src/watcher/RepositoryWatcher_linux.cpp#L28
My use case is sometimes to use GitAhead to view the log as I issue git commands in a terminal. Many git commands can of course make significant changes without modifying the working directory (e.g. git checkout -b, git branch, git reset, etc.). I'm getting in the habit of Alt-Tab'ing to GitAhead and CTRL+R'ing to get it to refresh. I suggest indeed adding the .git filter explicitly as the comment considers so that new branches and resets for example will be picked up. Any concerns with that?

**Comment by Pictor13** [comment]
I support @jwestell 's suggestion too. We got used to auto-refresh by most git GUIs and I have the same issues when using git in a shell and gittyup as visual aid to understand what happens or what I'm doing.

**Comment by Croydon** [comment]
Gitahead is no longer in development. 

I would personally recommend using Gittyup and there is a new issue for this here: https://github.com/Murmele/Gittyup/issues/216
